version: '3.3'
services:
  # nginx:
  #   build: ./nginx
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   depends_on:
  #     - frontend
  mysql:
    image: mysql:8.3
    restart: always
    env_file:
      - ./.env
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"

  frontend:
    build: .
    env_file:
      - ./.env
    environment:
      - WAIT_HOSTS=mysql:3306
      - WAIT_HOSTS_TIMEOUT=180
      - WAIT_SLEEP_INTERVAL=5
      - DB_NAME=${MYSQL_DATABASE}
      - DB_USER=root
      - DB_PASS=${MYSQL_ROOT_PASSWORD}
      - DB_SERVICE=mysql
      - DB_PORT=3306
    depends_on:
      - mysql
    ports:
      - '80:8080'
  engine:
    build: 
      context: ./engine
      dockerfile: dockerfile
    ports:
      - '4000:8080'
    environment:
    - ROCKET_LOG=debug
    - ROCKET_ADDRESS=0.0.0.0
    - ROCKET_PORT=8080
    - ROCKET_SECRET_KEY=xoYbrxK0ry7unoU97dX/Efk+nitNMtOU5796J112FT8=

    tty: true
    volumes:
      - ./engine/BlueBrilliant/src:/usr/src/blue_brilliant/src
    