# Use the official Nginx image from Docker Hub
FROM nginx:latest

# Remove the default Nginx configuration file
RUN rm /etc/nginx/conf.d/default.conf

# Copy the custom configuration file from the host machine to the container
COPY nginx.conf /etc/nginx/conf.d

# Copy the SSL certificates into the container
COPY ssl/nginx.crt /etc/ssl/certs/
COPY ssl/nginx.key /etc/ssl/private/

# Expose port 443 for SSL traffic
EXPOSE 443